#!/usr/bin/env bash
#
# Generates input for FillingJars exercise

N=${1:-1000000}
M=${2:-1000}
K=${3:-1000}

echo "$N $M"
for abc in $(seq 1 $M); do
  a=$(shuf -i  1-$N -n1)
  b=$(shuf -i $a-$N -n1)
  k=$(shuf -i  0-$K -n1)
  echo "$a $b $k"
done
